# Generated by Django 3.1.3 on 2023-01-22 21:07

import apps.Empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('idEmpleado', models.AutoField(auto_created=True, primary_key=True, serialize=False)),
                ('fotografia', models.ImageField(blank=True, max_length=255, null=True, upload_to=apps.Empleados.models.upload_to)),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=20)),
                ('ns', models.CharField(blank=True, max_length=16, null=True)),
                ('departamento', models.CharField(choices=[('Tejido', 'Tejido'), ('Corte', 'Corte'), ('Plancha', 'Plancha'), ('Empaque', 'Empaque'), ('Transporte', 'Transporte'), ('Diseno', 'Diseño'), ('Gerencia', 'Gerencia')], default='Tejido', max_length=20)),
                ('tipo', models.CharField(choices=[('Trabajador', 'Trabajador'), ('Encargado', 'Encargado'), ('Administrador', 'Administrador')], default='Trabajador', max_length=20)),
                ('gafete', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
