# Generated by Django 3.1.3 on 2023-01-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empleados', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empleado',
            name='tipo',
        ),
    ]
