# Generated by Django 3.1.3 on 2023-01-29 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicaluser',
            name='contrasena',
        ),
        migrations.RemoveField(
            model_name='user',
            name='contrasena',
        ),
    ]
