# Generated by Django 3.1.3 on 2023-01-30 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Empleados', '0002_remove_empleado_tipo'),
        ('Maquinas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpleadoMaquina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idEmpleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Empleados.empleado')),
                ('idMaquina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Maquinas.maquina')),
            ],
        ),
    ]
